{
    "name": "Conadex Print Spec",
    "version": "19.0.1.0.0",
    "summary": "Maestros de dominio para imprenta: spec de producto, acabados, papel y máquinas.",
    "author": "Conadex",
    "website": "",
    "category": "Manufacturing",
    "license": "OPL-1",
    "depends": ["product", "mrp", "stock", "maintenance"],
    "post_init_hook": "post_init_hook",
    "data": [
        "security/print_spec_security.xml",
        "security/ir.model.access.csv",
        "data/print_finishing_data.xml",
        "data/print_sheet_size_data.xml",
        "views/print_sheet_size_views.xml",
        "views/print_finishing_operation_views.xml",
        "views/print_finishing_line_views.xml",
        "views/product_template_views.xml",
        "views/mrp_bom_views.xml",
        "views/mrp_workcenter_views.xml",
        "views/print_spec_menus.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
